'number' + 23 + 32 // 'number2332' -> string
41 + 1 + 'number' // '42number' -> string
null + 1 // 1 -> number
'five' + + 'two' // 'fiveNaN' -> string
2 && 7 // 7 -> number
+'40' + +'2'; // 42 -> number
'10' - 5 === 6; // false - Boolean
true + false // 1 -> number
'4px' - 3 // NaN -> NaN
'4' - 3 // 1 - number
'2' + 3 ** 2; // '29' -> string
12 / '6' // 2 -> number
23 + 42 + 'number' // '65number' -> string
'10' + (5 === 6); // '10false' -> string
'number' + 15 + 3 // 'number153' -> string